### ISSUE TITLE
CuDNN error

### ISSUE THREAD

**Issue by fsluckymao** [bgshih/aster#19]
Hi @bgshih : when i run python aster/demo.py i encounter this error: 
Loaded runtime CuDNN library: 7103 (compatibility version 7100) but source was compiled with 7005 (compatibility version 7000).  If using a binary install, upgrade your CuDNN library to match.  If building from sources, make sure the library loaded at runtime matches a compatible version specified during compile configuration.
i will be greateful if you could give some advise.

**Comment by LinanYaooo** [comment]
I've solved it, by checking:
$ conda list
I found my cudnn version is 7.1.5, as it  said I should degrade my cudnn version.
$ conda install cudnn=7.0.5 to the matched version, then retry
Good Luck.

**Comment by 461807914** [comment]
> 
> 
> I've solved it, by checking:
> $ conda list
> I found my cudnn version is 7.1.5, as it said I should degrade my cudnn version.
> $ conda install cudnn=7.0.5 to the matched version, then retry
> Good Luck.

Thanks for your solution!!!  It work!
